dist: focal
language: cpp

compiler:
  - gcc

notifications:
  email: false

before_install:
  - sudo apt update
  - sudo apt remove --purge cmake
  - sudo apt install libboost-all-dev

install:    
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.1-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.17.1-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.17.1-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_EXAMPLE_GAUSS_NEWTON_NLLS=ON -DBUILD_EXAMPLE_README=ON
  - cmake --build . --config Release --target GaussNewtonNlls
  - cmake --build . --config Release --target ReadMe
  - sudo make install
